// File: src/utils/bookData.ts
import { Book } from '../types';

export const ALL_BOOKS: Book[] = [
  { id: '1', title: 'The Midnight Library', author: 'Matt Haig', genre: 'Fantasy', cover: 'https://placehold.co/300x450/A78BFA/FFFFFF?text=Midnight+Library', summary: 'Between life and death, there is a library where you can choose a different life. Nora Seed gets a chance to undo her regrets and try out new lives.', reviews: [{user: 'Reader1', text:'Absolutely captivating! A must-read.', rating:5}], prices: {'Amazon': '$12.99', 'B&N': '$13.50'}, published: '2020-08-13'},
  { id: '2', title: 'Project Hail Mary', author: 'Andy Weir', genre: 'Sci-Fi', cover: 'https://placehold.co/300x450/FBBF24/FFFFFF?text=Project+Hail+Mary', summary: 'An astronaut wakes up on a solo mission to save humanity, with no memory of who he is or how he got there. He must work with an unlikely alien ally.', reviews: [{user: 'SciFiFan', text:'Thrilling and scientifically accurate!', rating:5}], prices: {'Amazon': '$14.00', 'B&N': '$15.00'}, published: '2021-05-04' },
  { id: '3', title: 'Klara and the Sun', author: 'Kazuo Ishiguro', genre: 'Sci-Fi', cover: 'https://placehold.co/300x450/34D399/FFFFFF?text=Klara+and+Sun', summary: 'Klara, an Artificial Friend with outstanding observational qualities, watches the world from her store, hoping a customer will choose her.', reviews: [{user: 'BookWorm', text:'A poignant and thought-provoking read.', rating:4}], prices: {'Amazon': '$11.50', 'B&N': '$12.00'}, published: '2021-03-02' },
  { id: '4', title: 'The Invisible Life of Addie LaRue', author: 'V.E. Schwab', genre: 'Fantasy', cover: 'https://placehold.co/300x450/F472B6/FFFFFF?text=Addie+LaRue', summary: 'A young woman makes a Faustian bargain to live forever, but is cursed to be forgotten by everyone she meets. Until she meets a man who remembers her.', reviews: [{user: 'FantasyLover', text:'Captivating and beautifully written.', rating:5}], prices: {'Amazon': '$10.99', 'B&N': '$11.99'}, published: '2020-10-06' },
  { id: '5', title: 'Atomic Habits', author: 'James Clear', genre: 'Self-Help', cover: 'https://placehold.co/300x450/60A5FA/FFFFFF?text=Atomic+Habits', summary: 'An easy & proven way to build good habits & break bad ones. This book offers practical strategies for improving every day.', reviews: [{user: 'ProductivityGeek', text:'Life-changing insights!', rating:5}], prices: {'Amazon': '$15.00', 'B&N': '$16.50'}, published: '2018-10-16' },
  { id: '6', title: 'Where the Crawdads Sing', author: 'Delia Owens', genre: 'Mystery', cover: 'https://placehold.co/300x450/818CF8/FFFFFF?text=Crawdads+Sing', summary: 'A young woman who raised herself in the marshes of the Deep South becomes a suspect in the murder of a local celebrity.', reviews: [{user: 'MysteryFan', text:'A beautiful story with a gripping mystery.', rating:4}], prices: {'Amazon': '$9.50', 'B&N': '$10.00'}, published: '2018-08-14' },
  { id: '7', title: 'Dune', author: 'Frank Herbert', genre: 'Sci-Fi', cover: 'https://placehold.co/300x450/6EE7B7/FFFFFF?text=Dune', summary: 'Set in the distant future, Dune tells the story of Paul Atreides, whose family accepts control of the desert planet Arrakis. A saga of political intrigue, mysticism, and environmentalism.', reviews: [{user: 'OldSchoolSciFi', text:'A masterpiece of science fiction.', rating:5}], prices: {'Amazon': '$10.00', 'B&N': '$11.00'}, published: '1965-08-01' },
  { id: '8', title: 'The Great Gatsby', author: 'F. Scott Fitzgerald', genre: 'Classic', cover: 'https://placehold.co/300x450/FDBA74/FFFFFF?text=Gatsby', summary: 'A novel about the Jazz Age, focusing on the mysterious millionaire Jay Gatsby and his unrequited love for Daisy Buchanan.', reviews: [{user: 'LitLover', text:'A timeless classic.', rating:4}], prices: {'Amazon': '$8.00', 'B&N': '$9.00'}, published: '1925-04-10' },
  { id: '9', title: 'Educated', author: 'Tara Westover', genre: 'Memoir', cover: 'https://placehold.co/300x450/A5B4FC/FFFFFF?text=Educated', summary: 'An unforgettable memoir about a young girl who, kept out of school by her survivalist family, leaves home to pursue education, and discovers the power of knowledge.', reviews: [{user: 'InspirationSeeker', text:'Incredible true story.', rating:5}], prices: {'Amazon': '$13.50', 'B&N': '$14.00'}, published: '2018-02-20' },
  { id: '10', title: 'The Alchemist', author: 'Paulo Coelho', genre: 'Fiction', cover: 'https://placehold.co/300x450/FBCFE8/FFFFFF?text=Alchemist', summary: 'A philosophical novel about a young Andalusian shepherd boy named Santiago who journeys in search of a hidden treasure in the Egyptian pyramids.', reviews: [{user: 'Philosopher', text:'Deeply inspiring.', rating:4}], prices: {'Amazon': '$9.00', 'B&N': '$9.50'}, published: '1988-01-01' },
];
